#cloud-config
users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin, microk8s
    home: /home/ubuntu
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCUBo+qnNu5xxM9vfz4C04M36FHxHNrEMdm5TkFj1/SfVtqunlUOeMpu7nFCZZKnX8HYwf/MkjcBiTYAgncxku8grwl6XuW/pcvmb6/ghSIaw4xtRRSzit7omqJ5d8kXB3+Nd1aaMHsjfly4nkaqswhySVXQqr8Hw6DbWVw8jLLVKEE+5NZHY33hJkhJwK4blCllsGpmQaKi1qxjsN0hZOWNK01iJAydwD8t2xJ0NOYbq8Qas5IyPnRN7SPxvEhIP6WLQ6Ym6Dmf8FwNW1cHLTKabgjzt5f/HKUkKS89dPd3fn4nnFli1BOMECGUIvVlOw2pQNri7+04OOfn2FGlqr5
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDOv0NA/YZvPfx8D0dvq/ihLor+flB/+0WZtLezXonS+RVrUn6r3FBqmHD+O0ebTcwz82l/ckDFbQhWxorP4jRISo6ZmMLItJbi5XR78w6yQzQHrBd6lOfI+hzpEPKFEMOax48w28WhHd7jcDQgyDSMb8IKpuUAioPVOmXhaJr/1ZNLdtua4ZIaVqgabFV2Br2Oi3u8S/4JtE8EU9pvtCvZ8pkyseI6OiQhajJAu3m9nJCYBIwwl7f8qVmDNSNru2yvQ4BROcK2kZkBMk9dfF5fSD2hzCibKVS4XtYX2h0BGlwkD5yJk20104ibnUkk483TOsM7Yu9NLXu1uKkgI6dB
groups:
  - microk8s
system_info:
  default_user:
    groups: [microk8s]
ssh_pwauth: false
disable_root: false
package_update: true
package_upgrade: true
packages:
  - curl
runcmd:
  - alias kubectl='microk8s kubectl'
  - sudo snap install microk8s --classic
  - mkdir /home/ubuntu/.kube
